// ─── Sample Filipino Food Products ───────────────────────────────────────────

import { AddOn, Product } from '@/types';

export const SAMPLE_ADDONS: AddOn[] = [
    { id: 'ao1', name: 'Extra Rice', price: 20 },
    { id: 'ao2', name: 'Extra Sauce', price: 15 },
    { id: 'ao3', name: 'Atchara', price: 25 },
    { id: 'ao4', name: 'Soup', price: 30 },
    { id: 'ao5', name: 'Drinks Upgrade', price: 35 },
];

export const SAMPLE_PRODUCTS: Product[] = [
    // ─── Main Foods ───────────────────────────────────────────────────────────
    {
        id: 'p1',
        name: 'Lechon Kawali',
        price: 180,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80',
        description: 'Crispy deep-fried pork belly',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },
    {
        id: 'p2',
        name: 'Adobo',
        price: 150,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1641543693563-5897c17c3a4f?w=400&q=80',
        description: 'Classic Filipino chicken adobo',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },
    {
        id: 'p3',
        name: 'Sinigang',
        price: 160,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
        description: 'Tamarind-based sour soup with pork',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },
    {
        id: 'p4',
        name: 'Kare-Kare',
        price: 200,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1625943553852-781c6313c68c?w=400&q=80',
        description: 'Oxtail peanut stew with vegetables',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },
    {
        id: 'p5',
        name: 'Crispy Pata',
        price: 350,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
        description: 'Deep-fried whole pork knuckle',
        availableSizes: ['Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },
    {
        id: 'p6',
        name: 'Pinakbet',
        price: 120,
        category: 'Main Foods',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
        description: 'Ilocano mixed vegetable dish',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: SAMPLE_ADDONS,
    },

    // ─── Desserts ─────────────────────────────────────────────────────────────
    {
        id: 'p7',
        name: 'Halo-Halo',
        price: 95,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1711297588985-7a70d09ef1d1?w=400&q=80',
        description: 'Mixed shaved ice dessert with milk',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },
    {
        id: 'p8',
        name: 'Leche Flan',
        price: 75,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&q=80',
        description: 'Creamy caramel egg custard',
        availableSizes: ['Small', 'Medium'],
        availableAddOns: [],
    },
    {
        id: 'p9',
        name: 'Biko',
        price: 60,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=400&q=80',
        description: 'Sweet sticky rice cake with latik',
        availableSizes: ['Small', 'Medium'],
        availableAddOns: [],
    },
    {
        id: 'p10',
        name: 'Turon',
        price: 50,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=400&q=80',
        description: 'Fried banana spring roll with jackfruit',
        availableSizes: ['Small', 'Medium'],
        availableAddOns: [],
    },

    // ─── Drinks ───────────────────────────────────────────────────────────────
    {
        id: 'p11',
        name: 'Calamansi Juice',
        price: 55,
        category: 'Drinks',
        image: 'https://images.unsplash.com/photo-1621506289937-a8e4d3c75696?w=400&q=80',
        description: 'Freshly squeezed Philippine lime juice',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },
    {
        id: 'p12',
        name: 'Buko Juice',
        price: 65,
        category: 'Drinks',
        image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&q=80',
        description: 'Fresh young coconut water',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },
    {
        id: 'p13',
        name: 'Sago at Gulaman',
        price: 45,
        category: 'Drinks',
        image: 'https://images.unsplash.com/photo-1607920592519-bab2a80a8f19?w=400&q=80',
        description: 'Tapioca pearl and jelly drink',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },
    {
        id: 'p14',
        name: 'Mango Shake',
        price: 85,
        category: 'Drinks',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80',
        description: 'Blended Carabao mango smoothie',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },

    // ─── Add-ons ──────────────────────────────────────────────────────────────
    {
        id: 'p15',
        name: 'Steamed Rice',
        price: 20,
        category: 'Add-ons',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
        description: 'Plain steamed white rice',
        availableSizes: ['Small', 'Medium', 'Large'],
        availableAddOns: [],
    },
    {
        id: 'p16',
        name: 'Ensalada',
        price: 45,
        category: 'Add-ons',
        image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
        description: 'Fresh green salad with vinegar dressing',
        availableSizes: ['Small', 'Medium'],
        availableAddOns: [],
    },
];
